<?php

if ( !defined('IN_PHPBB') )
{
die('Hacking attempt');
}

// --------------------------------------------------------------
// DOSYA ADI : lang_******.php
// TELÝF HAKKI : © 2000, 2005 Canver Networks [ phpBB Türkiye ]
// WWW : http://www.phpbbturkiye.com
// --------------------------------------------------------------

global $board_config;


$faq[] = array("--","Oturum ve Hesap Açma sorunlarý");
$faq[] = array("Neden oturum açamýyorum?", "Hesap açtýnýz mý? Oturum açabilmek için önceden hesap açmanýz gerek. Yoksa mesaj panosundan atýldýnýz mý (o halde bu anlamda bir mesaj görmeniz gerekir)? Eðer öyleyse, site veya pano yöneticisiyle irtibata geçip sebebini sorabilirsiniz. Eðer hesap açtýysanýz ve yasaklanmýþ olmamanýza raðmen oturum açamýyorsanýz, tekrar tekrar kullanýcý adýnýzý ve þifrenizi kontrol edin. Genelde hata burada oluyor. Sorun bu deðilse pano yöneticisiyle irtibata geçin, belki pano için yanlýþ ayar yapmýþ olabilir.");
$faq[] = array("Neden hesap açmam gerekiyor?", "Hesap açmanýza gerek olmayabilirdi aslýnda. Mesaj gönderebilmek için hesap açmanýn þart olmasý, pano yöneticisinin kararýna baðlý. Ayrýca hesap açýnca bazý özel imkanlara ulaþabilirsiniz. Örneðin mesajlarýnýzýn yanýnda kedinize ait küçük bir resim (avatar/sembol) gösterme, kiþisel mesaj gönderme, tanýdýðýnýz kullanýcýlara e-posta gönderme veya kullanýcý gruplarýna katýlma imkanlarýna misafir kullanýcýlar sahip deðildir. Hesap açma iþlemi çok basit olduðu için hesap açmanýz önerilir.");
$faq[] = array("Neden otomatik olarak oturum kapatýlýyor?", "Oturum açma sayfasýnda gördüðünüz <i>Beni hatýrla</i> komutunu seçmediðiniz sürece, mesaj panosu sizi sadece belirli bir süre için oturum açmýþ kabul eder. Böylece hesabýnýzýn baþkalarý tarafýndan kullanýlmasý önlenir. Oturumunuzun devamlý kalmasý için, bu komutu seçmeniz yeterlidir. Fakat baþka þahýslarýnda kullandýðý (örn. herhangi bir kütüphaneye, internet cafeye, üniversiteye vs. ait) bir bilgisayardan oturum açýyorsanýz yapýyorsanýz, bu komutu seçmemeniz önerilir.");
$faq[] = array("Kimler Çevrimiçi listesinde ismimin görülmesini nasýl önleyebilirim?", "Þahsýnýza ait hesabýnýz sayfasýnda <i>Çevrimiçi olduðumu gizle</i> seçeneðini bulabilirsiniz. Buradan <i>Evet</i> 'i seçince çevrimiçi olduðunuzu sadece pano yöneticileri ve kendiniz görebilirsiniz. Bu durumda gizli kullanýcý olarak sayýlýrsýnýz.");
$faq[] = array("Þifremi unuttum!", "Telaþa kapýlmayýn! Eski þifrenizi öðrenmek mümkün olmasa bile, yerine deðiþik bir þifre alabilirsiniz. Oturum açma sayfasýný açýp <u>Þifremi unuttum</u> üzerini týklayýn ve tarif edilen iþlemleri uygulayýn. Kýsa sürede tekrar çevrimiçi olduðunuzu göreceksiniz.");
$faq[] = array("Hesap açtým ama oturum açamýyorum!", "Ýlk önce kullanýcý adýnýzý ve þifrenizi doðru yazdýðýnýzý emin olun. Hesabýnýzýn onaylanmasý gerekebilir. Bazý mesaj panolarý tüm yeni açýlan hesaplarýn onaylanmasýný þart koþar. Oturum açabilmeniz yapabilmeniz için ya kendiniz ya da pano yöneticisi tarafýndan hesabýnýz onaylanmalýdýr. Bu durumda onay gerekçesi, hesap açma esnasýnda size bildirilmiþ olmalý. Bu doðrultuda bir e-posta aldýysanýz, tarif edilen iþlemleri uygulamanýz gerek. Eðer böyle bir e-posta almadýysanýz, verdiðiniz e-posta adresinin doðru olup olmadýðýný kontrol edin. Onay gerekçesinin sebebi, <i>kötü amaçlý</i> kullanýcýlarýn anonim kullanýcýlarýn panoyu suistimal etmelerini önlemektir. Verdiðiniz e-posta adresinin doðru olduðundan eminseniz, pano yöneticisiyle irtibata geçmeniz gerekir.");
$faq[] = array("Daha önceleri hesap açmýþtým ama artýk oturum açamýyorum!", "Bunun en olasý sebebi hatalý kullanýcý adý veya þifre giriþidir (hesap açtýktan sonra aldýðýnýz e-posta'ya bakýp kontrol edin). Belki de pano yöneticisi hesabýnýzý herhangi bir sebepten dolayý silmiþ olabilir. Panoya hiç mesaj gönderdiniz mi? Veritabanýnýn kapladýðý alaný küçük tutmak için, mesaj göndermeyen kullanýcýlarýn hesabý genelde belirli bir süre sonra silinir. Tekrar hesap açmayý deneyin.");

$faq[] = array("--","Kullanýcý Seçenekleri ve Ayarlarý");
$faq[] = array("Kullanýcý ayarlarýmý nasýl deðiþtirebilirim?", "Eðer hesap açtýysanýz bütün ayarlarýnýz veritabanýna kaydedilir. Ayarlarýnýzý deðiþtirmek için (genelde sayfalarýn üst kýsmýnda bulunan) <u>Hesabýnýz</u> linkini týklayýn. Ayarlarýnýz buradan deðiþtirilir.");
$faq[] = array("Gösterilen saatler yanlýþ!", "Gösterilen saatler büyük bir ihtimalle doðrudur. Fakat gördüðünüz saat, bulunduðunuz yerin saat diliminden farklý olabilir. Bu durumda, <u>Hesabýnýz</u> linkini týklayýp kendiniz için geçerli saat dilimini seçmeniz gerekir, örn. London, Paris, New York, Sydney vs. Çoðu seçenekler için geçerli olduðu gibi, saat dilimini deðiþtirme imkaný da sadece hesap açmýþ kullanýcýlara verilmiþtir.");
$faq[] = array("Deðiþik bir zaman dilimi seçtim ama saatler hala yanlýþ!", "Doðru zaman dilimini seçtiðinizden eminseniz ve saat hala yanlýþ gösteriliyorsa, bunun en olasý sebebi günýþýðýndan yararlanma deðiþimleri olabilir. Örn. yaz aylarýnda görülen saatler, bulunduðunuz ülkenin gerçek saatinden bir saat ileri veya geri olabilir. Mesaj panosu bu deðiþimleri dikkate almaz.");
$faq[] = array("Konuþtuðum lisan listede yok!", "Bunun en olasý sebepleri, pano yöneticisin konuþtuðunuz lisaný destekleyen uzantýyý kurmamýþ olabilir, ya da bu panonun konuþtuðunuz lisana henüz çevrilmiþ olmayýþýdýr. Pano yöneticilerine baþvurup, kendi lisanýnýzý destekleyen uzantýyý kurmalarýný rica edin. Eðer böyle bir uzantý yoksa, panoyu kendi dilinize çevirmekte özgürsünüz. Bu konuda daha geniþ bilgi için sayfalarýn alt kýsmýnda görülen phpBB Group linkini týklayýn.");
$faq[] = array("Ýsmimin altýnda resim (avatar/sembol) göstermek için ne yapmalýyým?", "Mesajlarýn görüntülendiði sayfalarda kullanýcý adlarýnýn altýnda iki tür resim görebilirsiniz. Birincisi, kullanýcý derecenizi gösterir ve genelde gönderdiðiniz mesaj sayýsýna baðlý olarak belirli bir sayýda yýldýz veya kare þeklindedir. Bunun altýnda kiþisel sembol denen biraz daha büyük bir resim görebilirsiniz. Bu resim genelde kullanýcýya ait ve özeldir. Kiþisel sembol kullanma imkanýný pano yöneticisi belirler. Ayrýca sembollerin ne þekilde kullanýlabileceðinide belirler. Sembol kullanamýyorsanýz, pano yöneticisine baþvurup bu imkaný ne sebepten iptal ettiðini öðrenebilirsiniz (bunun önemli bir sebebi olduðundan eminiz!)");
$faq[] = array("Kullanýcý derecemi nasýl deðiþtirebilirim?", "Genelde kullanýcý derecenizi doðrudan deðiþtirmeniz mümkün deðil (kullanýcý derecesi, gönderdiðiniz mesajýn yanýnda bulunan isminizin altýnda ve kullanýcý bilgileri sayfasýnda görülür). Çoðu mesaj panosunda kullanýcý dereceleri, gönderilen mesajlarýn sayýsýný veya yetkili üyeleri belirlemek için kullanýlýr, örn. yöneticiler veya pano yöneticileri özel bir dereceye sahip olabilir. Lütfen gereksiz yere mesaj gönderip, derecenizi yükseltmeye çalýþmayýn, elde edeceðiniz tek sonuç, yöneticilerin mesajlarýnýzýn sayýsýný düþürmesi olacaktýr.");
$faq[] = array("Bir kullanýcýnýn e-posta linkini týklayýnca oturum açmam isteniyor?", "Panoya ait e-posta formuyla maalesef sadece hesabý olan kullanýcýlar e-posta gönderebiliyor (ayrýca yöneticinin bu iþlevi çalýþtýrmasý gerek). Bunun sebebi, e-posta sisteminin anonim kullanýcýlar tarafýndan suistimal edilmesini önlemektir.");

$faq[] = array("--","Mesaj Gönderme");
$faq[] = array("Foruma yeni baþlýk nasýl gönderilir?", "Çok basit; forumu veya baþlýðý görüntüleme sayfasýnda <i>Yeni Baþlýk Gönder</i> düðmesini týklayýn. Yeni mesaj göndermeden önce hesap açmanýz gerekebilir. Forum ve baþlýk sayfalarýnýn alt kýsmýnda yapabileceðiniz bütün iþlemlerin listesini görebilirsiniz (örn. <i>Bu forumda yeni konular açabilirsiniz</i> vs. gibi).");
$faq[] = array("Mesajlar nasýl deðiþtirilir veya silinir?", "Pano yöneticisi veya bölüm yetkilisi olmadýðýnýz sürece, sadece kendinize ait mesajlarý deðiþtirebilir veya silebilirsiniz. Gönderdiðiniz bir mesajý <i>Mesajý Deðiþtir</i> düðmesini týklayarak deðiþtirebilirsiniz (bu imkan bazen sadece belirli bir süre için mevcuttur). Mesajýnýza birileri cevap göndermiþse eðer, mesajýnýzýn altýnda metni kaç defa deðiþtirdiðinizi gösteren kýsa bir yazý göreceksiniz. Mesajýnýz henüz yanýtlanmamýþsa, bu not görülmez. Ayrýca mesajýnýz pano yöneticileri veya bölüm yetkilileri tarafýndan deðiþtirilince de bu yazý görülmez (yöneticilerin böyle bir durumda metnin hangi kýsmýný ne sebepten dolayý deðiþtirdiklerini yazmalarý önerilir). Bir mesaja cevap geldikten sonra normal kullanýcýlar tarafýndan silinemez.");
$faq[] = array("Mesaj altýna imza nasýl eklenir?", "Herhangi bir mesaja imzanýzý ekleyebilmek için önce <i>Hesabýnýz</i> sayfanýza girip bir imza hazýrlamanýz gerek. Daha sonra mesaj gönderme formunun alt kýsmýndaki <i>Ýmzamý ekle</i> seçeneðini seçip mesajýnýza imzanýzý ekleyebilirsiniz. Gönderdiðiniz bütün mesajlara genel bir ayar olarak imzanýzýn eklenmesini istiyorsanýz, <i>Hesabýnýz</i> sayfasýndaki seçeneði týklayýn. Buna raðmen dilediðiniz her mesaj için imzanýzýn eklenmesini önleyebilirsiniz (mesaj gönderme formunda <i>Ýmzamý Ekle</i> seçeneðinin iþaretini kaldýrmanýz yeterli).");
$faq[] = array("Anket nasýl hazýrlanýr?", "Anket hazýrlamak çok basit: yeni bir baþlýk gönderirken (veya bir baþlýðýn ilk mesajýný deðiþtirirken - bu tabi yetkinize baðlý), mesaj gönderme formunun altýnda <i>Anket Ekle</i> formunu göreceksiniz (böyle bir formu göremiyorsanýz, anket ekleme yetkiniz yok demektir). Anket sorusunu ve en az iki tane anket þýkký eklemeniz gerekir. Anket þýkký eklemek için <i>Bu Þýkký Ekle</i> düðmesini týklayýn. Ayrýca anketin gösterim süresinide belirleyebilirsiniz, 0 (sýfýr) süresiz demektir. Eklenebilecek anket þýklarýnýn sayýsý sýnýrlýdýr. Bu sýnýrý pano yöneticisi belirler.");
$faq[] = array("Bir anket nasýl deðiþtirilir veya silinir?", "Anketler de mesajlar gibi sadece gönderen kullanýcý, bölüm yetkilisi veya pano yöneticisi tarafýndan deðiþtirilebilir. Bir anketi deðiþtirmek için, baþlýðýn ilk mesajýný týklayýn (ilgili anket daima bu mesaja baðlýdýr). Ankete henüz katýlan olmadýysa, hazýrlayan kullanýcý tarafýndan deðiþtirilebilir veya silinebilir. Ankete katýlan olmuþsa, sadece forum ve pano yöneticileri tarafýndan deðiþtirilebilir veya silinebilir. Böylece bir süre sonra þýklarý deðiþtirip anket sonuçlarýný sapýtma olanaðý kalmaz.");
$faq[] = array("Anketlere neden katýlamýyorum?", "Anketlere sadece hesabý olan kullanýcýlar katýlabilir (böylece hile yapma olanaðý önlenmiþ olur). Eðer hesap açmanýza olmanýza raðmen anketlere katýlamýyorsanýz, gerekli yetkilere sahip deðilsiniz demektir.");
$faq[] = array("Bazý forumlara neden ulaþamýyorum?", "Bazý forumlar sadece belirli kullanýcýlara veya kullanýcý gruplarýna açýk olabilir. Mesajlarý okumak, görüntülemek, göndermek için vs. özel yetki gerekebilir. Bu yetkiyi sadece pano yöneticileri verebilir, bu kiþilere baþvurmalýsýnýz.");

$faq[] = array("--","Biçimlendirme ve Baþlýk Tipleri");
$faq[] = array("Biçim Kodlarý (BBCode) nedir?", "Biçim Kodlarý HTML'in özel bir uygulamasýdýr. Forum'lara yazdýðýnýz mesajlarda Biçim Kodlarý kullanabilme imkanýný pano yöneticisi belirler. Ayrýca mesaj gönderme formundaki seçenekler sayesinde dilediðiniz mesajlarda Biçim Kodlarý'larýný iptal etmeniz mümkündür. Biçim Kodlarý, HTML'e benzer tarzdadýr fakat wtiketler &lt; ve &gt; yerine köþeli parantez içine alýnýr: [ ve ]. Ayrýca nelerin nasýl görüntülendiði daha iyi kontrol edilebilir. Biçim Kodlarý hakkýnda daha geniþ bilgiler için, mesaj gönderme sayfasýndan ulaþabileceðiniz <a href='faq.php?mode=bbcode' target='_blank'>rehbere</a> bakýnýz.");
$faq[] = array("HTML kullanabilir miyim?", "Pano yöneticisinin izin vermesine baðlýdýr, ilgili ayarlarýn tümünü o kontrol eder. Eðer izin verilmiþse, büyük ihtimalle sadece bazý etiketlerin çalýþtýðýný göreceksiniz. Böyle olmasý <i>güvenlik</i> içindir. Amaç, pano görüntüsünün bozulmasýný veya daha deðiþik sorunlarýn meydana gelmesini önlemektir. Ýzin verilmiþ olsa bile, mesaj gönderme formundaki seçenekler sayesinde dilediðiniz mesajlarda HTML'i iptal etmeniz mümkündür.");
$faq[] = array("Gülücük nedir?", "Gülücük (Smiley veya Emoticon), belirli duygu ifadelerini vermek için kullanýlan iþaretlerdir. Metinde küçük resimler halinde görüntülenir. Örn. :) mutlu, :( ise üzgün anlamýndadýr. Kullanabileceðiniz gülücüklerin <a href='posting.php?mode=smilies' target='_blank'>listesini</a> mesaj gönderme formunda görebilirsiniz. Gülücükleri aþýrý derecede kullanmamaya özen gösterin, yoksa metin okunmaz hale gelebilir. Bu durumda yönetici gülücükleri veya mesajýnýzý tamamýyla silmeye karar verebilir.");
$faq[] = array("Resim gönderebilir miyim?", "Gönderdiðiniz mesajla beraber resim de görüntülenebilir. Fakat þu anda panoya doðrudan resim göndermek mümkün deðildir. Bu yüzden umuma açýk bir web sitesinde kayýtlý bir resme link vermeniz gerek, örn. http://www.umuma-acik-site.net/resim.gif. Kendi bilgisayarýnýzda bulunan bir resme link vermeniz mümkün deðil. Ayrýca, umuma açýk olmayan ve sadece þifreyle ulaþýlan resimlere link vermek mümkün deðildir (örn. hotmail veya yahoo mailboxlarýnda vs. kayýtlý resimler). Resim görüntülemek için, Biçim Kodlarý'nýn [img] etiketini ya da (izin verilmiþse) HTML kullanabilirsiniz.");
$faq[] = array("Duyuru nedir?", "Duyurular çoðu zaman önemli bilgileri içerir, en kýsa zamanda okumanýzý öneririz. Duyurular, ilgili forumun her sayfasýnýn baþýnda görülür. Duyuru gönderebilmeniz için bu yetkiye sahip olmanýz gerek. Yetkilerinizi ise pano yöneticisi belirler.");
$faq[] = array("Önemli baþlýklar nedir?", "Önemli baþlýklar, ilgili forumun ilk sayfasýnda, duyurularýn hemen altýnda görülür. Çoðu zaman önemli bilgileri içerirler, mümkünse okumanýzý öneririz. Duyurular için geçerli olduðu gibi, herhangi bir foruma önemli baþlýk göndermek için gereken yetkileri pano yöneticisi belirler.");
$faq[] = array("Kilitli baþlýklar nedir?", "Bu baþlýklarý bölüm yetkilisi veya pano yöneticisi kilitler. Kilitli baþlýklarý yanýtlamak mümkün deðildir, içerdikleri anketler otomatik olarak sonlandýrýlýr. Baþlýklar birçok nedenden dolayý kilitlenmiþ olabilir.");

$faq[] = array("--","Kullanýcý Seviyeleri ve Gruplarý");
$faq[] = array("Pano yöneticileri nedir?", "Pano yöneticileri, panonun her bölümünde en çok yetkiye sahip olan þahýslardýr. Bu kiþiler, panonun her türlü iþlevini kontrol edebilir: izin verme, yetkilendirme, kullanýcý yasaklama, kullanýcý gruplarý ekleme, bölüm yetkilisi yetkilerini verme vs. Ayrýca bütün forumlarda bölüm yetkilisi yetkilerine sahiptirler.");
$faq[] = array("Bölüm yetkilileri nedir?", "Bölüm yetkilileri, günlük olarak forumun çalýþmasýný kontrol eden þahýslar veya gruplardýr. Baþlýklarý deðiþtirme ve silme yetkisine sahiptirler. Ayrýca yönettikleri forumdaki baþlýklarý kilitleyebilir, taþýyabilir, silebilir ve bölebilirler. Genelde bölüm yetkililerinin görevi, <i>off-topic</i>, yani baþlýk konusuyla ilgisi olmayan yanýtlarýn veya hakaret ve saldýrý niteliðindeki metinlerin gönderilmesini önlemektir.");
$faq[] = array("Kullanýcý gruplarý nedir?", "Kullanýcý gruplarý, pano yöneticilerinin kullanýcýlarý grup halinde ayýrabilmesi için öngörülen bir yöntemdir. Her kullanýcý (çoðu panolardan farklý olarak) birçok gruba üye olabilir. Bu þekilde pano yöneticileri belirli kullanýcýlara rahatlýkla bölüm yetkilisi yetkilerini veya özel forumlara ulaþma yetkisini vs. verebilir.");
$faq[] = array("Bir kullanýcý grubuna nasýl üye olabilirim?", "Bir kullanýcý grubuna üye olmak için, sayfa baþýndaki kullanýcý gruplarý linkine týklayýn. Kullanýcý gruplarýnýn listesini göreceksiniz. Gruplarýn tümü <i>eriþime açýk</i> olmayabilir, bazýlarý kilitli veya gizli olabilir. Grup açýk ise, ilgili düðmeyi týklayarak üye olmak için istekte bulunabilirsiniz. Ýsteðinizin kullanýcý grubu yöneticisi tarafýndan onaylanmasý gerekir, örneðin isteðinizin nedenini sorabilir. Ýsteðiniz reddedilirse grup yöneticisini lütfen rahatsýz etmeyin, bunun nedenleri olsa gerek.");
$faq[] = array("Bir kullanýcý grubunun yöneticisi olmak için ne yapmam gerek?", "Kullanýcý gruplarý pano yöneticisi tarafýndan açýlýr. Pano yöneticisi ayný zamanda her grubun yöneticisini belirler. Eðer yeni bir kullanýcý grubu açmak istiyorsanýz, ilk önce pano yöneticisiyle irtibata geçmeniz gerek, kendisine kiþisel mesaj göndermeyi deneyin.");

$faq[] = array("--","Kiþisel Mesajlar");
$faq[] = array("Kiþisel mesaj gönderemiyorum!", "Bunun üç sebebi olabilir: henüz hesap açmamýþ veya oturum açmamýþsýnýz, veya pano yöneticisi bütün pano için kiþisel mesajlarý iptal etmiþ. Üçüncü olanak ise: pano yöneticisi sizin bu imkaný kullanmanýzý önlemiþ olabilir, bu durumda kendisine nedenini sorabilirsiniz.");
$faq[] = array("Ýstemediðim kiþisel mesajlarý almaya devam ediyorum!", "Ýleride kiþisel mesajlar sistemine belirli kiþilerden gelen mesajlarý iptal etme imkanýný ekleyeceðiz. Þimdilik herhangi bir þahýstan istemediðiniz kiþisel mesajlar alýyorsanýz, pano yöneticisine baþvurun. O herhangi bir kullanýcýyý kiþisel mesaj göndermekten men edebilir.");
$faq[] = array("Bu mesaj panosunda hesabý olan birinden spam e-posta aldým!", "Üzgünüz, aslýnda bu panonun sunduðu e-posta gönderme iþlevi bundan korunmak için birçok önlemi almýþ bulunuyor. Aldýðýnýz spam e-posta'nýn bir kopyasýný pano yöneticisine gönderin. Özellikle aldýðýnýz e-posta'nýn baþlýk kýsmýný (to (kime), subject (konu) vs.) iletmeyi unutmayýn, bu kýsýmda e-posta'yý gönderen kullanýcý hakkýnda bilgiler bulunur. Pano yöneticisi bu bilgilerle meseleyi takip edebilir.");

$faq[] = array("--","Eklentiler");
$faq[] = array("Eklentileri nasýl yükleyebilirim?", "Yeni bir mesaj gönderirken eklenti yükleyebilirsiniz. Ana mesaj gönderme penceresinde <i>Eklenti Yükle</i> butonunu göreceksiniz. Buna týkladýðýnýzda <i>Gözat...</i> penceresi açýlýcak ve bilgisayarýnýzdan bu dosyayý seçebiliceksiniz. Eklemek istediðiniz dosyayý açýlan gözat penceresinden bulun, dosyayý seçin ve tamam butonuna basýn, çift týklamak veya o dosyayý seçip aç tuþuna basmak; hangisi kolayýnýza geliyorsa ya da bilgisayarýnýz hangisini destekliyorsa onu yapýn. Eklenti için açýklama yapmak için <i>Dosya açýklamasý</i> kýsmýný kullanabilirsiniz. Eðer pano yöneticisi çoklu eklenti seçeneðine izin veriyorsa ayný iþlemleri yaparak bir mesaj için pano yöneticisinin belirlediði maksimum sayýda eklentiyi gönderebilirsiniz.<br/><br/>Forum yöneticisi dosya boyutu, dosya uzantýsý ve gönderilen eklentiler için bir üst limit belirler. Göderdiðiniz eklentilerin pano kurallarýna aykýrý olmamasý sizin sorumluluðunuzdur. Yöneticiler; gönderdiðiniz eklenti pano kurallarýna uymadýðý takdirde eklentinizi sizi bu konuda uyarmadan silebilirler.<br/><br/>Þunu unutmayýnki sitenin sahibi, webmaster, pano yöneticisi ya da moderatörler veri kayýplarý yüzünden sorumlu tutulamaz.");
$faq[] = array("Gönderdiðim bir mesaj için sonradan eklenti nasýl eklerim?", "Bunu yapmak için gönderdiðiniz mesajý düzenlemelisiniz. Yeni eklenti, <i>Gönder</i> butonuna basýldýktan sonra düzenlenmiþ mesaja eklenecektir.");
$faq[] = array("Eklenti nasýl silerim?", "Eklenti silmek için mesajýnýzý düzenlemelisiniz ve silmek istediðiniz eklentiyi <i>Gönderilmiþ Eklentiler</i> kutusundan bulup <i>Eklenti Sil</i> butonuna basmalýsýnýz. Eklenti, düzenlediðiniz mesajdaki <i>Gönder</i> butonuna bastýðýnýzda silinicektir.");
$faq[] = array("Bir eklentinin açýklamasýný nasýl güncellerim?", "Bir eklentinin açýklamasýný güncellemek için gönderdiðiniz mesajý düzenlemelisiniz, <i>Dosya Açýklamasý</i> yazan kýsmý düzenleyerek ve daha sonra Göderilmiþ Eklentiler kutusu içinde <i>Açýklamayý güncelle</i> butonuna basarak istediðiniz eklentinin açýklamasýný güncelleyebilirsiniz. Eklentinin açýklamasý, <i>Gönder</i> butonuna basýldýðýnda düzenlenmiþ mesaj için güncelleþtirilicektir.");
$faq[] = array("Neden benim eklentim mesajlarda görünmüyor?", "Bunun baþlýca sebebi dosyanýn ya da uzantýsýnýn forumda kullanýlmasýna artýk izin verilmiyor olmasýdýr. Moderatör veya yönetici tarafýndan forum kurallarýna aykýrý olduðu için silinmiþ de olabilir.");
$faq[] = array("Neden eklenti ekleyemiyorum?", "Bazý forumlarda eklentileri ekleyebilmek belli kullanýcý ya da kullanýcý gruplarýna limitlendirilmiþtir. Eklentileri ekleyebilmek için size özel yetki verilmiþ olmalýdýr, sadece forum moderatörleri ve forum yöneticisi bu izni vermeye yetkilidir, onlarla iletiþim kurabilirsiniz.");
$faq[] = array("Gerekli izinlere sahibim, neden eklenti yükleyemiyorum?", "Pano yöneticisi dosya boyutu ya da uzantýsý için forumda bir üst limit belirlemiþ olabilir. Moderatör ya da pano yöneticisi yetkilerinizi deðiþtirmiþ olabilir ya da eklenti yüklemeyi yasaklamýþ olabilir. Eklenti yüklemeye çalýþýrken bu hatayla ilgili gerekli açýklama yapýlýcaktýr, yapýlmazsa forum moderatörü ya da pano yöneticisiyle iletiþim kurabilirsiniz.");
$faq[] = array("Neden eklenti silemiyorum?", "Bazý forumlarda eklentileri silebilmek belli kullanýcý ya da kullanýcý gruplarýna limitlendirilmiþtir. Eklentileri silebilmek için size özel yetki verilmiþ olmalýdýr, sadece forum moderatörleri ve pano yöneticisi bu izni vermeye yetkilidir, onlarla iletiþim kurabilirsiniz.");
$faq[] = array("Neden eklentileri görüp, indiremiyorum?", "Bazý forumlarda eklentileri görüp, indirebilmek belli kullanýcý ya da kullanýcý gruplarýna limitlendirilmiþtir. Eklentileri görmek ya da indirebilmek için size özel yetki verilmiþ olmalýdýr, sadece forum moderatörleri ya da pano yöneticisi bu izni vermeye yetkilidir, onlarla iletiþim kurabilirsiniz.");
$faq[] = array("Yasal olmayan eklentiler için kimlerle iletiþim kurmalýyým?", "Pano yöneticisiyle iletiþim kurmalýsýnýz. Eðer pano yöneticisinin kim olduðunu bulamýyorsanýz öncelikle moderatörlerle iletiþim kurup bu konuda kiminle iletiþim kuracaðýnýzý sorabilirsiniz. Hala cevap alamadýysanýz domain\'in sahibi ile iletiþime geçebilirsiniz. Eðer bu bir bedava site ise (örnek yahoo, free.fr, f2s.com, vb.), yönetim departmaný ya da suç departmanýyla iletiþim kurabilirsiniz. Unutmayalým ki phpBB Grubu bu forum sisteminin kimler tarafýndan nasýl ve nerede kullanýldýðýný bilemez. Yasal yardýmlar için phpBB Grubu ile iletiþim kurmak anlamsýzdýr. Bu gibi olaylarýn phpbb.com internet sitesi ve phpBB yazýlýmý ile ilgisi yoktur. Eðer phpBB Grubuna üçüncü kullaným durumlarýnda mail atarsanýz ya kýsa bir cevap alýrsýnýz ya da hiç alamazsýnýz.");

// Password security
$faq[] = array("--", "Modlar için yardým");
$faq[] = array("Parola güvenliði ne demektir?", "Bu fonksiyon size parolanýzýn güvenlik düzeyini gösterir ve güvenli bir parola üretmenizde yardýmcý olur. Fonksiyonun sunduðu deðerler bir tavsiyeden ibarettir. Siz yine de dilediðiniz parolayý kullanmakta özgürsünüz.");
$faq[] = array("Nasýl güvenli bir parola üretebilirim?", "Güvenli bir parola için ipuçlarý:<br />- Parolanýz en azýndan 6 karakter ve en fazla 32 karakterden oluþmalýdýr ve Harf, rakam, iþaret kombinasyonlarýndan oluþmalýdýr.<br />- Parolanýz en azýndan 4 karakter uzunluðunda olmalý ve sayý ya da iþaret olarak en azýndan diðer türlerden birinden 2 karakter içermelidir.<br />- Ýngilizce dil yapýsýnda bulunmayan, türkçeye veya baþka dillere mahsus özel karakterler, md5 yapýsý gereði boþ karakterlere çevirilmektedir. Bu sebeple bu tip belli dillere mahsus karakterler (Ç,ç,Ð,ð,ý,Ý,Ö,ö,Þ,þ,Ü,ü) ve þapkalý ifadeler (â,î,û vs.) tavsiye edilmez.<br />- Ne adýnýzý ne de kullanýcý adýnýzý parola olarak kullanmayýn.<br />- Klavyede birbiri ardýna gelen karakterler yapýlarýný kullanmayýn. Örn F: KMLY, Örn Q: QERTY<br />- Popüler þiir kitaplarda bulunan meþhur þiir pasajlarýnda oluþmamalýdýr. Örn: ben sana mecburum bilemezsin. <br />- Radyo ve Tv'de kullanýlan popüler slagonlarý kullanmaktan kaçýnýnýz. Örn Kurtlar vadisi ýrak: abi ilerde çevirme var :) <br />- BÜYÜK küçük karakterlerin karýþýmýndan oluþan þifreleri tercih ediniz.<br />- Güvenli bir parolayý oluþturduktan sonra onu bir yerlere yazmayýnýnýz.");
$faq[] = array("E-posta adresi doðrulanamadý", "E-posta adresiniz online olarak, bir e-posta mesajý gönderilecek kontrol edilmektedir. Girdiðiniz e-posta adresi hatalý ise veya mesaj kutunuz dolu ise bu hatayý alabilirsiniz. Farklý bir e-posta adresiyle kayýt olmayý deneyebilirsiniz. Ayrýntýlý bilgi için forum yöneticisiyle irtibata geçiniz.");
$faq[] = array("E-posta sunucusuyla baðlantý kurulamadý", "E-posta sunucunuza baðlanma iþlemi gerçekleþtirilemiyor, bu sebeple bu hatayý alýyorsunuz. Bu hatayý bir çok sebeple verebilir. E-posta sunucusu kapalý olabilir, yanlýþ bir e-posta adresi girmiþ olabilirsiniz veya forum ayarlarý doðru yapýlanmamýþ olabilir. Ayrýntýlý bilgi için forum yöneticisiyle irtibata geçiniz. ");

$faq[] = array("--","Yakusha ile ilgili Konular");
$faq[] = array("Yakusha ismi nerden gelmektedir?", "<b>Yakusha</b> ismi japon kültüründen bir parça olmakla beraber, ayný zamanda bir kýz isminin þifrelenmiþ bir kullaným þeklidir.");
$faq[] = array("Yakusha nedir?", "<b>Yakusha</b>, phpBB üzerinden geliþtirilmiþ geliþmiþ bir mesaj panosu sistemidir.");
$faq[] = array("Yakusha mesaj panosu sistemini nerden bulabilirim?", "<b>Yakusha</b> mesaj panosu sistemini <a href=\"http://www.yakusha.net\" target=\"_blank\">www.yakusha.net</a> adresinden bulabilirsiniz.");
$faq[] = array("Yakusha mesaj panosu sistemine nerden destek bulabilirim?", "  <a href=\"http://www.yakusha.net\" target=\"_blank\">Yakusha Destek forumlarýndan</a> ve <a href=\"http://www.canver.net\">phpBB Türkiye</a> forumlarýndan <b>gönüllü</b> destek bulabilirsiniz.");
$faq[] = array("Ýstediðim MOD neden yok?", "Gerekli görülen MODlar periyodik olarak yayýnlanan yeni sürümlerle ilave edilmektedir. Eðer bir MODun gerekli olduðuna inanýyorsanýz <a href=\"http://www.yakusha.net\" target=\"_blank\">sitemizi ziyaret ederek</a> isteðinizi belirtebilirsiniz.");
$faq[] = array("Kullanýlan mod güncel deðil?", "Sistemde kullanýlan bir modun güncel olmadýðýndan þüpheleniyorsanýz lütfen <a href=\"http://www.yakusha.net\" target=\"_blank\">Yakusha destek forumlarýna</a> bildiriniz.");
$faq[] = array("Mesaj panosunda açýk buldum?", "Konuyla ilgili bir güncelleme var mý araþtýrýnýz. Eðer bir güncelleme yoksa lütfen <a href=\"http://www.yakusha.net\" target=\"_blank\">Yakusha destek forumlarýna</a> konuyu bildiriniz.");

$faq[] = array("--","phpBB2 ile ilgili Konular");
$faq[] = array("Bu mesaj panosunu kim yazdý?", "Bu yazýlým (deðiþtirilmemiþ haliyle) <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a> tarafýndan üretilmiþ ve genel daðýtýma çýkarýlmýþtýr. Tüm eser haklarý phpBB Group'a aittir. Bu eser, '<a href=\"http://www.gnu.org/copyleft/gpl.html/\" target=\"_blank\">GNU General Public Licence</a>' lisansýna uygun olarak eriþime açýlmýþtýr. Bu lisansa uyma þartýyla ücretsiz daðýtýlabilir.");
$faq[] = array("Bu mesaj panosunu kim Türkçeleþtirdi?", "Kullandýðýnýz Türkçe dil dosyalarý (deðiþtirilmemiþ haliyle) '<a href=\"http://www.phpbbturkiye.com/\" target=\"_blank\">phpBB Türkiye</a>' tarafýndan üretilmiþ ve genel daðýtýma çýkarýlmýþtýr. Tüm eser haklarý '<a href=\"http://www.phpbbturkiye.com/\" target=\"_blank\">phpBB Türkiye</a>'ye aittir. Bu dosyalar, '<a href=\"http://www.gnu.org/copyleft/gpl.html/\" target=\"_blank\">GNU General Public Licence</a>' lisansýna uygun olarak eriþime açýlmýþtýr. Bu lisansa uyma þartýyla ücretsiz daðýtýlabilir, ancak dosyalardaki imza ve copyright bilgileri deðiþtirilemez.");

$faq[] = array("--", "Teþekkürler");
$faq[] = array("Bu yardýmcý bilgiler için kime veya kimlere teþekkür edebilirim?", "&#9642; <a href='http://www.phpbb.com/' target='_blank'>phpBB Group</a> - phpBB Resmi Sitesi.<br /> &#9642; <a href='http://www.canver.net' target='_blank'>phpBB Türkiye</a> - phpBB yazýlýmýnýn Türkçe Desteðini saðlar.");

?>