<?php

if ( !defined('IN_PHPBB') )
{
die('Hacking attempt');
}

// --------------------------------------------------------------
// DOSYA ADI : lang_******.php
// TELÝF HAKKI : © 2000, 2005 Canver Networks [ phpBB Türkiye ]
// WWW : http://www.phpbbturkiye.com
// --------------------------------------------------------------

$faq[] = array("--","Giriþ");
$faq[] = array("Biçim Kodlarý nedir?", "Biçim Kodlarý, HTML'in özel bir uygulamasýdýr. Forumlara yazdýðýnýz mesajlarda Biçim Kodlarý kullanabilme imkanýný pano yöneticisi belirler. Ayrýca mesaj gönderme formundaki seçenekler sayesinde dilediðiniz mesajlarda Biçim Kodlarý'ný iptal etmeniz mümkündür. Biçim Kodlarý, HTML'e benzer tarzdadýr fakat etiketler &lt; ve &gt; yerine köþeli parantez içine alýnýr. Ayrýca nelerin nasýl görüntülendiði daha iyi kontrol edilebilir. Mesajlarýnýza Biçim Kodlarý eklemek için mesaj gövdesi üzerinde bulunan araç çubuðunu kullanmanýz iþi çok daha kolaylaþtýrýr (araç çubuðu görünümü kullandýðýnýz tema'ya baðlýdýr). Ayrýca alttaki rehberi faydalý bulabilirsiniz.");

$faq[] = array("--","Metin Biçimini Deðiþtirme");
$faq[] = array("Kalýn, eðik veya altýçizili yazýlar nasýl yazýlýr?", "Biçim Kodlarý, metnin temel biçimlemesini kolayca deðiþtirmenizi saðlayan etiketlere sahiptir. Bunu gerçekleþtirmek için þu yöntemler kullanýlýr: <ul><li>Metnin belirli bir kýsmýný kalýn harflerle görüntülemek için <b>[b][/b]</b> etiketleri içine alýn, örn. <br /><br /><b>[b]</b>Merhaba<b>[/b]</b><br /><br />yazýlýnca <b>Merhaba</b> olarak görüntülenir.</li><li>Altýçizili yazýlar için <b>[u][/u]</b> kullanýn, örn.: <br /><br /><b>[u]</b>Günaydýn<b>[/u]</b><br /><br />yazýlýnca <u>Günaydýn</u> olarak görüntülenir.</li><li>Metni eðik yazmak için <b>[i][/i]</b> kullanýn, örn. <br /><br />Çok <b>[i]</b>Büyük!<b>[/i]</b><br /><br />yazýlýnca sonuç Çok <i>Büyük!</i> olur.</li></ul>");
$faq[] = array("Yazýlarýn rengi veya boyutu nasýl deðiþtirilir?", "Yazýlarýn renk veya boyutunu deðiþtirmek için alttaki etiketler kullanýlabilir. Elde edilen sonuç, kullanýlan web tarayýcýsý ve bilgisayar sistemine göre deðiþebilir, aklýnýzda bulunsun: <ul><li>Yazýlarýn rengi, metni <b>[color=][/color]</b> etiketleri içine alarak deðiþtirilir. Belirli ingilizce renk isimlerini (örn. red, blue, yellow vs.) veya alternatif olarak 16 tabanlý sayý sisteminde (HEX) kodlanmýþ üç rakamlý renk kodunu yazabilirsiniz (örn. #FFFFFF, #000000). Metni örneðin kýrmýzý harflerle yazmak için:<br /><br /><b>[color=red]</b>Merhaba!<b>[/color]</b><br /><br />veya<br /><br /><b>[color=#FF0000]</b>Merhaba!<b>[/color]</b><br /><br />ayný þekilde görüntülenir: <span style=\"color:red\">Merhaba!</span></li><li>Karakterlerin boyutunu benzer þekilde <b>[size=][/size]</b> kullanarak deðiþtirebilirsiniz. Bu etiket kullandýðýnýz tema'ya baðlýdýr. Karakterlerin pixel olarak boyutunu yazmanýz önerilir. Bu rakam 1 ile baþlayýp (gözle görülmeyecek kadar küçük), en fazla 29 (çok büyük) olabilir. Örnek:<br /><br /><b>[size=9]</b>KÜÇÜK<b>[/size]</b><br /><br />genelde þu sonucu verir: <span style=\"font-size:9px\">KÜÇÜK</span><br /><br />öte yandan:<br /><br /><b>[size=24]</b>BÜYÜK!<b>[/size]</b><br /><br /><span style=\"font-size:24px\">BÜYÜK!</span> sonucunu verir.</li></ul>");
$faq[] = array("Biçimlendirme etiketlerini karýþtýrabilir miyim?", "Evet, mesela dikkati çekmek için þöyle yazabilirsiniz:<br /><br /><b>[size=18][color=red][b]</b>DÝKKAT!<b>[/b][/color][/size]</b><br /><br />Bu yazý þu þekilde görüntülenir: <span style=\"color:red;font-size:18px\"><b>DÝKKAT!</b></span><br /><br />Uzun metinleri bu þekilde yazmamanýzý öneririz! Unutmayýn ki, etiketlerin düzgün bir þekilde kapatýlmasýný temin etmek, metni gönderen kiþi olarak sizin görevinizdir. Örneðin bu þekilde yazmak yanlýþtýr: <br /><br /><b>[b][u]</b>Etiketler hatalý kapatýlmýþ<b>[/b][/u]</b>");

$faq[] = array("--","Alýntý ile Cevap ve Eþaralýklý Yazýtipi");
$faq[] = array("Alýntý ile cevap yazma", "Bir metinden alýntý yapmanýn iki ayrý yöntemi vardýr: kaynak vererek veya vermeyerek.<ul><li>Bir mesaja cevap vermek için Alýnýtý ile Cevap komutunu kullanýrsanýz, orijinal mesajýn kendi mesajýnýza <b>[quote=\"\"][/quote]</b> etiketleri arasýnda eklendiðini göreceksiniz. Bu yöntem, bir þahsý veya seçeceðiniz herhangi baþka bir yeri kaynak vererek yanýt yazmanýzý saðlar. Örneðin Ali isminde bir þahsýn yazdýklarýný alýntý etmek için þu þekilde yazmanýz gerek: <br /><br /><b>[quote=\"Ali\"]</b>Ali'nin yazdýðý yazýlar...<b>[/quote]</b><br /><br />Sonuçta alýntý yapýlan kýsmýn önüne otomatik olarak Ali demiþki: yazýlýr. Alýntý yaptýðýnýz þahsýn ismini týrnak iþaretleri \"\" içine almayý unutmayýn, týrnak iþaretleri kullanmanýz <b>þart</b>.</li><br /><br /><li>Ýkinci yöntem, kaynak vermeden alýntý yapmanýzý saðlar. Ýlgili bölümü <b>[quote][/quote]</b> etiketleri içine almanýz yeterli. Bu bölümün önünde Alýntý: yazýsýný göreceksiniz.</li></ul>");
$faq[] = array("Kaynak yazýlým veya eþaralýklý yazýtipiyle görüntüleme", "Bir programlama dilinde yazýlmýþ kaynak yazýlým veya eþaralýklý yazýtipi (örn. Courier) gerektiren herhangi bir metni görüntülemek için, ilgili kýsmý <b>[code][/code]</b> etiketleri içine almalýsýnýz. Örn.: <br /><br /><b>[code]</b>echo \"Bu bizim kodumuz\";<b>[/code]</b><br /><br /><b>[code][/code]</b> etiketleri arasýna yazýlan tüm biçimleme etiketleri (örn. [i], [b] gibi) iptal edilir. Bu biçimlendirmenin kullandýðý yazýtipi, kullandýðýnýz temaya göre farklýlýk gösterebilir.");

$faq[] = array("--","Liste Ekleme");
$faq[] = array("Madde imiyle liste", "Biçim Kodlarý rakamsýz (madde imiyle) ve rakamlý olmak üzere iki türlü liste destekler. Bu listeler aslýnda HTML listelerine eþittir. Rakamsýz liste, her maddeyi bir madde imiyle beraber satýr baþýný biraz girintilenmiþ olarak görüntüler. Rakamsýz bir liste hazýrlamak için <b>[list][/list]</b> etiketlerini kullanýn ve her satýrýn baþýna <b>[*]</b> yazýn. Örn. sevdiðiniz renklerin bir listesini þu þekilde hazýrlayabilirsiniz:<br /><br /><b>[list]</b><br /><b>[*]</b>Kýrmýzý<br /><b>[*]</b>Mavi<br /><b>[*]</b>Sarý<br /><b>[/list]</b><br /><br />Sonuç olarak þu listeyi göreceksiniz:<ul><li>Kýrmýzý</li><li>Mavi</li><li>Sarý</li></ul>");
$faq[] = array("Rakamlý liste", "Ýkinci liste türü olan rakamlý listeyle, her satýr baþýnda görülen rakamý kontrol edebilirsiniz. Rakamlara göre sýralanmýþ bir liste için <b>[list=1][/list]</b> kullanmanýz gerek. Alternatif olarak alfabe'ye göre sýralanmýþ bir liste için <b>[list=a][/list]</b> etiketlerini kullanabilirsiniz. Rakamsýz listelerde olduðu gibi, her maddeyi <b>[*]</b> ile iþaretlemeniz gerek. Örneðin:<br /><br /><b>[list=1]</b><br /><b>[*]</b>Maðazaya git<br /><b>[*]</b>Yeni bilgisayar al<br /><b>[*]</b>Eve götür<br /><b>[/list]</b><br /><br />þu þekilde görüntülenir:<ol type=\"1\"><li>Maðazaya git</li><li>Yeni bilgisayar al</li><li>Eve götür</li></ol>Öte yandan alfabeye göre sýralanmýþ bir listeyi þu þekilde yazmanýz gerekir:<br /><br /><b>[list=a]</b><br /><b>[*]</b>Birinci seçenek<br /><b>[*]</b>Ýkinci seçenek<br /><b>[*]</b>Üçüncü seçenek<br /><b>[/list]</b><br /><br />Sonuç:<ol type=\"a\"><li>Birinci seçenek</li><li>Ýkinci seçenek</li><li>Üçüncü seçenek</li></ol>");

$faq[] = array("--", "Link (URL) Ekleme");
$faq[] = array("Ayrý bir siteye link verme", "Biçim Kodlarý link (URL) eklemek için deðiþik yöntemleri destekler.<ul><li>Birinci yöntem <b>[url=][/url]</b> etiketidir. = iþaretinin arkasýna yazýlanlar link olarak çalýþýr. Örneðin phpBB.com'a link vermek için þu þekilde yazýn:<br /><br /><b>[url=http://www.phpbb.com/]</b>phpBB'yi ziyaret edin!<b>[/url]</b><br /><br />Sonuçta þu linki göreceksiniz: <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB'yi ziyaret edin!</a> Bu linki týklayýnca ayrý bir pencere açýlýr. Böylece kullanýcý panoyu gezmeye devam edebilir.</li><li>Link adresinin gösterilmesini istiyorsanýz, þu þekildede yazabilirsiniz:<br /><br /><b>[url]</b>http://www.phpbb.com/<b>[/url]</b><br /><br />Sonuçta þu linki göreceksiniz: <a href=\"http://www.phpbb.com/\" target=\"_blank\">http://www.phpbb.com/</a></li><li>phpBB ayrýca <i>Sihirli Linkler</i> denen bir iþleme sahip. Bunun sayesinde, kurallara uygun bir þekilde yazýlan her link adresi otomatik olarak link'e çevrilir, herhangi bir etiket, hatta http:// yazmanýza gerek kalmaz. Örn. www.phpbb.com yazýnca, izlenim sayfasýnda otomatik olarak <a href=\"http://www.phpbb.com/\" target=\"_blank\">www.phpbb.com</a> olarak görüntülenir.</li><li>Ayný iþlem email adresleri için uygulanýr. Dilerseniz özel olarak bir adres belirleyebilirsiniz, örn.:<br /><br /><b>[email]</b>no.one@domain.adr<b>[/email]</b><br /><br />yazýlýnca þu þekilde görüntülenir: <a href=\"emailto:no.one@domain.adr\">no.one@domain.adr</a> Veya basitçe no.one@domain.adr yazabilirsiniz ve mesajýnýz görüntülendiðinde bu kýsým otomatik olarak link'e çevrilir.</li></ul>Bütün Biçim Kodlarý etiketleri gibi, link adreslerini de diðer etiketlerin içine alabilirsiniz, örn. <b>[img][/img]</b> (bir sonraki madde bakýn), <b>[b][/b]</b>, vs. Biçimleme etiketlerinde olduðu gibi, etiketlerin düzgün bir þekilde sýrasýyla kapatýlmasýný kendiniz saðlamalýsýnýz, örn.:<br /><br /><b>[url=http://www.phpbb.com/][img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/url][/img]</b><br /><br />doðru <u>deðildir</u> ve hatta mesajýnýzýn silinmesine yol açabilir, bu konuda dikkatli olmanýz gerek.");

$faq[] = array("--", "Mesajlarda Resim Görüntüleme");
$faq[] = array("Bir mesaja resim ekleme", "Biçim Kodlarý mesajlarýnýza resim eklemek için bir etikete sahiptir. Bu etiketi kullanýrken iki önemli noktayý dikkate almanýz gerek: Birçok kullanýcý mesajlarda çok sayýda resmin görüntülenmesini hoþ karþýlamýyor. Ayrýca kullanmak istediðiniz resme internet üzerinden ulaþýlabilmeli (örn. bu resmin kendi bilgisayarýnýzda bulunmasý yeterli deðildir). Þu anda phpBB üzerinden resim kaydetme imkaný yoktur (bu konular muhtemelen phpBB'nin bir sonraki sürümünde ele alýnacak). Bir resmi görüntülemek için, resmin adresini <b>[img][/img]</b> etiketleri içine almalýsýnýz. Örn.:<br /><br /><b>[img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/img]</b><br /><br />Bir önceki maddede belirtildiði gibi, resmi dilerseniz <b>[url][/url]</b> etiketleri içine alabilirsiniz. Örn.:<br /><br /><b>[url=http://www.phpbb.com/][img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/img][/url]</b><br /><br />yazýnca þu sonucu verir:<br /><br /><a href=\"http://www.phpbb.com/\" target=\"_blank\"><img src=\"templates/subSilver/images/logo_phpBB_med.gif\" border=\"0\" alt=\"\" /></a><br />");

$faq[] = array("--", "Diðer Konular");
$faq[] = array("Kendi etiketlerimi ekleyebilir miyim?", "Hayýr, maalesef phpBB 2.xx sürümünde böyle bir imkan yok. Bir sonraki sürümde özelleþtirilmiþ Biçim Kodlarý etiketleri sunmayý planlýyoruz.");

$faq[] = array("--", "<a name=\"tables\"></a>Tablolar ve Tablo Etiketleri");
$faq[] = array("[table] [/table] etiketleri nasýl kullanýlýr?", "Bir tablo baþlatmak için [table] [/table] etiketini kullanýnýz. Tablo baþlangýcýnda [table] etiketini, tablonun sonunda [/table] etiketini kullanýlýr.");
$faq[] = array("[mrow] etiketi nasýl kullanýlýr?", "Bir baþlýklý sütunla (ortalý, koyu text) baþlayan yeni bir satýr için [mrow] etiketi kullanýlýr. <br />Not: [/mrow] etiketi zorunlu DEÐÝLDÝR.<br /><br /><b><u>Örneðin:</u></b><br /><br />[table]<b>[mrow]</b>Ana Satýr[/table]etiketi<br /><br /><table align=\"top\" cellpadding=\"2\" cellspacing=\"0\" style=\"font-size: 12px\" border=\"1\" bgcolor=\"#FFFFFF\"><tr><td style=\"font-weight: bold; text-align: center;\">Ana Satýr</td></tr></table><br /> gibi bir görüntü oluþturur.");
$faq[] = array("[mcol] etiketi nasýl kullanýlýr?", "Her baþlýklý sutun için (ortalý, koyu metin) [mcol] etiketi kullanýlýr<br />Not: [/mcol] etiketi zorunlu DEÐÝLDÝR. <br /><br /><b><u>Örneðin:</u></b><br /><br /> [table][mrow]Ana Satýr Hücre 1<b>[mcol]</b>Ana Satýr Hücre 2[col]Ana Satýr Hücre 3[/table] etiketi<br /><br /><table align=\"top\" cellpadding=\"2\" cellspacing=\"0\" style=\"font-size: 12px\" border=\"1\" bgcolor=\"#FFFFFF\"><tr><td style=\"font-weight: bold; text-align: center;\">Ana Satýr Hücre 1</td><td style=\"font-weight: bold; text-align: center;\">Ana Satýr Hücre 2</td><td style=\"font-weight: bold; text-align: center;\">Ana Satýr Hücre 3</td></tr></table><br /> gibi bir görüntü oluþturur");
$faq[] = array("[row] etiketi nasýl kullanýlýr?", "Her yeni satýr (basit, ortalý deðil) için [row] etiketi kullanýlýr.<br />Not: [/row] etiketi zorunlu DEÐÝLDÝR<br /><br /><b><u>Örneðin:</u></b><br /><br />[table][mrow]Ana Satýr<b>[row]</b>Geçerli Satýr[/table] etiketi<br /><br /><table align=\"top\" cellpadding=\"2\" cellspacing=\"0\" style=\"font-size: 12px\" border=\"1\" bgcolor=\"#FFFFFF\"><tr><td style=\"font-weight: bold; text-align: center;\">Ana Satýr</td></tr><tr><td>Geçerli Satýr</td></tr></table><br /> gibi bir görüntü oluþturur.");
$faq[] = array("[col] etiketi nasýl kullanýlýr?", "[col] etiketi yeni bir sutun (basit, ortalý deðil) yapmak  için kullanýlýr<br />Not:[/col] etiketi zorunlu DEÐÝLDÝR.<br /><br /><b><u>Örnek:</u></b><br /><br /> [table][mrow]Ana Satýr 1[mcol]Ana Satýr 2[row]Geçerli Satýr 1<b>[col]</b>Geçerli Satýr 2[/table] etiketleri<br /><br /><table align=\"top\" cellpadding=\"2\" cellspacing=\"0\" style=\"font-size: 12px\" border=\"1\" bgcolor=\"#FFFFFF\"><tr><td style=\"font-weight: bold; text-align: center;\">Ana Satýr 1</td><td style=\"font-weight: bold; text-align: center;\">Ana Satýr 2</td></tr><tr><td>Geçerli Satýr 1</td><td>Geçerli Satýr 2</td></tr></table><br /> gibi bir görüntü oluþturur.");
$faq[] = array(" [mrow], [mcol], [row], [col] etiketlerine kapatma etiketi eklemem gerekir mi?", "Hayýr, [table] etiketi, gerekli olan [/table] kapatma etiketi dýþýndaki herhangi bir kapatma etiketine ihtiyaç duymaz.");
$faq[] = array("Farklý ekitetler veya özellikler var mý?", "Herhangi bir table etiketi ile<a href=\"#color\">\"color=\"</a> ve <a href=\"#fontsize\">\"fontsize=\"</a> etiketlerini kullanabilirsiniz. HTML etiketlerindeki gibi etiketleri birbirinden tek boþluk ile ayýrarak kullanmanýz gerekmektedir. Geçersiz kullaným þekilleri istenen görüntünün oluþmasýna engel olacaktýr.<br /><br /><a name=\"color\"><br /></a><span style=\"font-size: 16px\"><b><u>Color</u></b></span><br /><br />\"color=\" etiketi arka plan rengini deðiþtirmeye izin verir. <br />Özelleþmiþ renk isimlerini kullanabilirsiniz (Örnek: red, blue, yellow, vs.) veya hexadecimal renk deðerlerini kullanabilirsiniz. Örnek: #FFFFFF, #000000.<br /><br /><b><u>Örnek:</u></b><br />[table color=blue][mrow color=green]Ana Satýr 1[mcol color=red]Ana Satýr 2[row color=#00FF00]Geçerli Satýr 1[col color=#FF0000]Geçerli Satýr 2[row]Geçersiz Satýr 1[col]Geçersiz Satýr 2[/table] etiketleri<br /><br /><table align=\"top\" cellpadding=\"2\" cellspacing=\"0\" style=\"font-size: 12px\" border=\"1\" bgcolor=\"#0000FF\"><tr bgcolor=\"#00FF00\"><td style=\"font-weight: bold; text-align: center;\">Ana Satýr 1</td><td bgcolor=\"#FF0000\" style=\"font-weight: bold; text-align: center;\">Ana Satýr 2</td></tr><tr bgcolor=\"#FF0000\"><td>Geçerli Satýr 1</td><td bgcolor=\"#00FF00\">Geçerli Satýr 2</td></tr><tr><td>Geçersiz Satýr 1</td><td>Geçersiz Satýr 2</table><br />gibi bir görüntü oluþturur.<br /><hr><br /><a name=\"fontsize\"></a><br /><span style=\"font-size: 16px\"><b><u>Fontsize</u></b></span><br /><br />\"fontsize=\" etiketi metin boyutunu deðiþtirmeye izin verir.<br />Varsayýlan olarak font size deðeri geçerli tema dosyasýnda genellikle, FONTSIZE3 olarak gelmektedir. Bu deðeri deðiþtirmek için [table] etiketi üstünde kimi etiketleri kullanmanýz gerekmektedir. <br /><br /><b><u>Örnek:</u></b><br />[table fontsize=18][mrow fontsize=10]Ana Satýr 1[mcol fontsize=14]Ana Satýr 2[row fontsize=5]Geçerli Satýr 1[col fontsize=28]Geçerli Satýr 2[row]Geçersiz Satýr 1[col]Geçersiz Satýr 2[/table] etiketleri<br /><br /><table align=\"top\" cellpadding=\"2\" cellspacing=\"0\" style=\"font-size: 18px\" border=\"1\" bgcolor=\"#FFFFFF\"><tr style=\"font-size: 10px\"><td style=\"font-weight: bold; text-align: center;\">Ana Satýr 1</td><td  style=\"font-weight: bold; text-align: center; font-size: 14px\">Ana Satýr 2</td></tr><tr style=\"font-size: 5px\"><td>Geçerli Satýr 1</td><td style=\"font-size: 28px\">Geçerli Satýr 2</td></tr><tr><td>Geçersiz Satýr 1</td><td>Geçersiz Satýr 2</table><br /> gibi bir görüntü oluþturur.");//

// This ends the BBCode guide entries
//

?>